# This workflow will scrape and process new report data from https://www.mass.gov/lists/weekly-inmate-count-2020.

name: Refresh Data and Rebuild Site

on:
  push:
    branches: [master]
  schedule:
    - cron: 0 18 * * *

jobs:
  refreshdata:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and process new data
        run: python -m scraper

      - name: Add downloaded data to git
        working-directory: ./
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "workflows/refreshdata"
          git add .
          git diff-index --quiet HEAD || git commit -m "Save new report data"

      - name: Push data
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploysite:
    needs: refreshdata
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: gatsby build

      - name: Deploy site to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
